services:
  dev:
    build:
      dockerfile: ./scripts/docker/dev.Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-registry.cn-hangzhou.aliyuncs.com/117503445-mirror/dev@sha256:c6c775812ba23bd9a2b3afa0015e66d3acec3230d210f37945b9f26235d6f0db}
    volumes:
      - ./:/workspace
      - cache:/root/.cache
      - cursor:/root/.cursor-server
      - vscode:/root/.vscode-server
      - docker:/var/lib/docker
      - ./scripts/entrypoint.sh:/entrypoint
    privileged: true
volumes:
  cache:
  cursor:
  docker:
  vscode: