services:
  dev:
    build:
      dockerfile: ./scripts/docker/dev.Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-117503445/dev-desktop}
    volumes:
      - ./:/workspace
      - cache:/root/.cache
      - cursor:/root/.cursor-server
      - vscode:/root/.vscode-server
      - docker:/var/lib/docker
      - ./scripts/entrypoint.sh:/entrypoint
    privileged: true
volumes:
  cache:
  cursor:
  docker:
  vscode: