version: 3

tasks:
  dashboard-run:
    desc: "运行 Dashboard 服务"
    deps: [":base:clear", ":build:bin"]
    cmds:
      - pkill -f "./data/dashboard/dashboard" || true
      - sleep 1
      - ./data/dashboard/dashboard

  dashboard-background:
    desc: "在后台运行 Dashboard 服务"
    deps: [":base:clear", ":build:bin"]
    cmds:
      - pkill -f "./data/dashboard/dashboard" || true
      - sleep 1
      - ./data/dashboard/dashboard &
      - sleep 2