// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/rpc/template.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 根据 RPC 类型填充对应 payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiResponse_Healthz
	Payload       isApiResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_pkg_rpc_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponse) GetPayload() isApiResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiResponse) GetHealthz() *HealthzResponse {
	if x != nil {
		if x, ok := x.Payload.(*ApiResponse_Healthz); ok {
			return x.Healthz
		}
	}
	return nil
}

type isApiResponse_Payload interface {
	isApiResponse_Payload()
}

type ApiResponse_Healthz struct {
	Healthz *HealthzResponse `protobuf:"bytes,3,opt,name=healthz,proto3,oneof"`
}

func (*ApiResponse_Healthz) isApiResponse_Payload() {}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_pkg_rpc_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{1}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_pkg_rpc_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{2}
}

func (x *HealthzResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_pkg_rpc_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{3}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_pkg_rpc_template_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{4}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	HubPort       int32                  `protobuf:"varint,2,opt,name=hub_port,json=hubPort,proto3" json:"hub_port,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pkg_rpc_template_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{5}
}

func (x *AgentInfo) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentInfo) GetHubPort() int32 {
	if x != nil {
		return x.HubPort
	}
	return 0
}

func (x *AgentInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

var File_pkg_rpc_template_proto protoreflect.FileDescriptor

const file_pkg_rpc_template_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/rpc/template.proto\x12\apkg.rpc\"|\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\ahealthz\x18\x03 \x01(\v2\x18.pkg.rpc.HealthzResponseH\x00R\ahealthzB\t\n" +
	"\apayload\"\x10\n" +
	"\x0eHealthzRequest\"+\n" +
	"\x0fHealthzResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x13\n" +
	"\x11ListAgentsRequest\"@\n" +
	"\x12ListAgentsResponse\x12*\n" +
	"\x06agents\x18\x01 \x03(\v2\x12.pkg.rpc.AgentInfoR\x06agents\"]\n" +
	"\tAgentInfo\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x19\n" +
	"\bhub_port\x18\x02 \x01(\x05R\ahubPort\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online2\x92\x01\n" +
	"\x0fTemplateService\x128\n" +
	"\aHealthz\x12\x17.pkg.rpc.HealthzRequest\x1a\x14.pkg.rpc.ApiResponse\x12E\n" +
	"\n" +
	"ListAgents\x12\x1a.pkg.rpc.ListAgentsRequest\x1a\x1b.pkg.rpc.ListAgentsResponseB,Z*github.com/117503445/dashboard/pkg/rpc;rpcb\x06proto3"

var (
	file_pkg_rpc_template_proto_rawDescOnce sync.Once
	file_pkg_rpc_template_proto_rawDescData []byte
)

func file_pkg_rpc_template_proto_rawDescGZIP() []byte {
	file_pkg_rpc_template_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_template_proto_rawDesc), len(file_pkg_rpc_template_proto_rawDesc)))
	})
	return file_pkg_rpc_template_proto_rawDescData
}

var file_pkg_rpc_template_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_rpc_template_proto_goTypes = []any{
	(*ApiResponse)(nil),        // 0: pkg.rpc.ApiResponse
	(*HealthzRequest)(nil),     // 1: pkg.rpc.HealthzRequest
	(*HealthzResponse)(nil),    // 2: pkg.rpc.HealthzResponse
	(*ListAgentsRequest)(nil),  // 3: pkg.rpc.ListAgentsRequest
	(*ListAgentsResponse)(nil), // 4: pkg.rpc.ListAgentsResponse
	(*AgentInfo)(nil),          // 5: pkg.rpc.AgentInfo
}
var file_pkg_rpc_template_proto_depIdxs = []int32{
	2, // 0: pkg.rpc.ApiResponse.healthz:type_name -> pkg.rpc.HealthzResponse
	5, // 1: pkg.rpc.ListAgentsResponse.agents:type_name -> pkg.rpc.AgentInfo
	1, // 2: pkg.rpc.TemplateService.Healthz:input_type -> pkg.rpc.HealthzRequest
	3, // 3: pkg.rpc.TemplateService.ListAgents:input_type -> pkg.rpc.ListAgentsRequest
	0, // 4: pkg.rpc.TemplateService.Healthz:output_type -> pkg.rpc.ApiResponse
	4, // 5: pkg.rpc.TemplateService.ListAgents:output_type -> pkg.rpc.ListAgentsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_rpc_template_proto_init() }
func file_pkg_rpc_template_proto_init() {
	if File_pkg_rpc_template_proto != nil {
		return
	}
	file_pkg_rpc_template_proto_msgTypes[0].OneofWrappers = []any{
		(*ApiResponse_Healthz)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_template_proto_rawDesc), len(file_pkg_rpc_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_template_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_template_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_template_proto_msgTypes,
	}.Build()
	File_pkg_rpc_template_proto = out.File
	file_pkg_rpc_template_proto_goTypes = nil
	file_pkg_rpc_template_proto_depIdxs = nil
}
