// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/rpc/template.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 根据 RPC 类型填充对应 payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiResponse_Healthz
	Payload       isApiResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_pkg_rpc_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{0}
}

func (x *ApiResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponse) GetPayload() isApiResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiResponse) GetHealthz() *HealthzResponse {
	if x != nil {
		if x, ok := x.Payload.(*ApiResponse_Healthz); ok {
			return x.Healthz
		}
	}
	return nil
}

type isApiResponse_Payload interface {
	isApiResponse_Payload()
}

type ApiResponse_Healthz struct {
	Healthz *HealthzResponse `protobuf:"bytes,3,opt,name=healthz,proto3,oneof"`
}

func (*ApiResponse_Healthz) isApiResponse_Payload() {}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_pkg_rpc_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{1}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_pkg_rpc_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_template_proto_rawDescGZIP(), []int{2}
}

func (x *HealthzResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_pkg_rpc_template_proto protoreflect.FileDescriptor

const file_pkg_rpc_template_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/rpc/template.proto\x12\apkg.rpc\"|\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\ahealthz\x18\x03 \x01(\v2\x18.pkg.rpc.HealthzResponseH\x00R\ahealthzB\t\n" +
	"\apayload\"\x10\n" +
	"\x0eHealthzRequest\"+\n" +
	"\x0fHealthzResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2K\n" +
	"\x0fTemplateService\x128\n" +
	"\aHealthz\x12\x17.pkg.rpc.HealthzRequest\x1a\x14.pkg.rpc.ApiResponseB,Z*github.com/117503445/dashboard/pkg/rpc;rpcb\x06proto3"

var (
	file_pkg_rpc_template_proto_rawDescOnce sync.Once
	file_pkg_rpc_template_proto_rawDescData []byte
)

func file_pkg_rpc_template_proto_rawDescGZIP() []byte {
	file_pkg_rpc_template_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_template_proto_rawDesc), len(file_pkg_rpc_template_proto_rawDesc)))
	})
	return file_pkg_rpc_template_proto_rawDescData
}

var file_pkg_rpc_template_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_rpc_template_proto_goTypes = []any{
	(*ApiResponse)(nil),     // 0: pkg.rpc.ApiResponse
	(*HealthzRequest)(nil),  // 1: pkg.rpc.HealthzRequest
	(*HealthzResponse)(nil), // 2: pkg.rpc.HealthzResponse
}
var file_pkg_rpc_template_proto_depIdxs = []int32{
	2, // 0: pkg.rpc.ApiResponse.healthz:type_name -> pkg.rpc.HealthzResponse
	1, // 1: pkg.rpc.TemplateService.Healthz:input_type -> pkg.rpc.HealthzRequest
	0, // 2: pkg.rpc.TemplateService.Healthz:output_type -> pkg.rpc.ApiResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_rpc_template_proto_init() }
func file_pkg_rpc_template_proto_init() {
	if File_pkg_rpc_template_proto != nil {
		return
	}
	file_pkg_rpc_template_proto_msgTypes[0].OneofWrappers = []any{
		(*ApiResponse_Healthz)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_template_proto_rawDesc), len(file_pkg_rpc_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_template_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_template_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_template_proto_msgTypes,
	}.Build()
	File_pkg_rpc_template_proto = out.File
	file_pkg_rpc_template_proto_goTypes = nil
	file_pkg_rpc_template_proto_depIdxs = nil
}
