// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/rpc/template.proto

package rpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	rpc "github.com/117503445/dashboard/pkg/rpc"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TemplateServiceName is the fully-qualified name of the TemplateService service.
	TemplateServiceName = "pkg.rpc.TemplateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TemplateServiceHealthzProcedure is the fully-qualified name of the TemplateService's Healthz RPC.
	TemplateServiceHealthzProcedure = "/pkg.rpc.TemplateService/Healthz"
	// TemplateServiceListAgentsProcedure is the fully-qualified name of the TemplateService's
	// ListAgents RPC.
	TemplateServiceListAgentsProcedure = "/pkg.rpc.TemplateService/ListAgents"
)

// TemplateServiceClient is a client for the pkg.rpc.TemplateService service.
type TemplateServiceClient interface {
	Healthz(context.Context, *connect.Request[rpc.HealthzRequest]) (*connect.Response[rpc.ApiResponse], error)
	ListAgents(context.Context, *connect.Request[rpc.ListAgentsRequest]) (*connect.Response[rpc.ListAgentsResponse], error)
}

// NewTemplateServiceClient constructs a client for the pkg.rpc.TemplateService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTemplateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TemplateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	templateServiceMethods := rpc.File_pkg_rpc_template_proto.Services().ByName("TemplateService").Methods()
	return &templateServiceClient{
		healthz: connect.NewClient[rpc.HealthzRequest, rpc.ApiResponse](
			httpClient,
			baseURL+TemplateServiceHealthzProcedure,
			connect.WithSchema(templateServiceMethods.ByName("Healthz")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[rpc.ListAgentsRequest, rpc.ListAgentsResponse](
			httpClient,
			baseURL+TemplateServiceListAgentsProcedure,
			connect.WithSchema(templateServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// templateServiceClient implements TemplateServiceClient.
type templateServiceClient struct {
	healthz    *connect.Client[rpc.HealthzRequest, rpc.ApiResponse]
	listAgents *connect.Client[rpc.ListAgentsRequest, rpc.ListAgentsResponse]
}

// Healthz calls pkg.rpc.TemplateService.Healthz.
func (c *templateServiceClient) Healthz(ctx context.Context, req *connect.Request[rpc.HealthzRequest]) (*connect.Response[rpc.ApiResponse], error) {
	return c.healthz.CallUnary(ctx, req)
}

// ListAgents calls pkg.rpc.TemplateService.ListAgents.
func (c *templateServiceClient) ListAgents(ctx context.Context, req *connect.Request[rpc.ListAgentsRequest]) (*connect.Response[rpc.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// TemplateServiceHandler is an implementation of the pkg.rpc.TemplateService service.
type TemplateServiceHandler interface {
	Healthz(context.Context, *connect.Request[rpc.HealthzRequest]) (*connect.Response[rpc.ApiResponse], error)
	ListAgents(context.Context, *connect.Request[rpc.ListAgentsRequest]) (*connect.Response[rpc.ListAgentsResponse], error)
}

// NewTemplateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTemplateServiceHandler(svc TemplateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	templateServiceMethods := rpc.File_pkg_rpc_template_proto.Services().ByName("TemplateService").Methods()
	templateServiceHealthzHandler := connect.NewUnaryHandler(
		TemplateServiceHealthzProcedure,
		svc.Healthz,
		connect.WithSchema(templateServiceMethods.ByName("Healthz")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceListAgentsHandler := connect.NewUnaryHandler(
		TemplateServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(templateServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pkg.rpc.TemplateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TemplateServiceHealthzProcedure:
			templateServiceHealthzHandler.ServeHTTP(w, r)
		case TemplateServiceListAgentsProcedure:
			templateServiceListAgentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTemplateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTemplateServiceHandler struct{}

func (UnimplementedTemplateServiceHandler) Healthz(context.Context, *connect.Request[rpc.HealthzRequest]) (*connect.Response[rpc.ApiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.TemplateService.Healthz is not implemented"))
}

func (UnimplementedTemplateServiceHandler) ListAgents(context.Context, *connect.Request[rpc.ListAgentsRequest]) (*connect.Response[rpc.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.TemplateService.ListAgents is not implemented"))
}
